# -*- coding: utf-8 -*-
"""1st Port Scanner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OG-WyqV7Fl2phhPpimHY1Dyxu9pDud9K
"""

# 1st Port Scanner


import socket
def port_scanner(target, port_range):

    for port in range(port_range[0], port_range[1] + 1):
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(3)
        result = s.connect_ex((target, port))

        if result == 0:
            print(f"Port {port} is open")
        else:
            print(f"Port {port} is closed")

        s.close()



target = input("Enter the target Ip Address")
port_range = (1, 65535 )
port_scanner(target, port_range)